version: '3'
services:
  dev:
    build: ./dev
    volumes: 
      - war_volume:/target/hello-1.0.war
  prod:
    image: tomcat:8-alpine
    ports: 
      - "8082:8080"
    volumes:
      - war_volume:/usr/local/tomcat/webapps/
    volumes:
      war_volume:

