version: '3'
services:
  dev:
    build: ./dev
    volumes: 
      - type: volume
        source: war_volume
        target: /boxfuse-sample-java-war-hello/
      
  prod:
    image: tomcat:8-alpine
    ports: 
      - "8082:8080"
    volumes:
      - type: volume
        source: war_volume
        target: /usr/local/tomcat/webapps
      
volumes:
  war_volume:

