version: '3'
volumes:
  war_volume:
services:
  dev:
    build: dev/
    volumes:
      - war_volume:/tmp/boxfuse-sample-java-war-hello/target/
      
  prod:
    image: tomcat:9-alpine
    ports: 
      - "8082:8080"
    volumes:
      - war_volume:/usr/local/tomcat9/webapps/
    depends_on:
      - dev